title_primary: "Stone's Blog" # the bigger text
title_secondary: "早睡早起" # the smaller text
keywords:

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: #username

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: #MTAyMC8zMTQzMi83OTk2  
disqus: suroot
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark


leancloud_visitors:
  enable: true
  app_id: tTi4cS0qum2R4N2aT7bLqOus-gzGzoHsz
  app_key: 8Qam7AaaDuHgsVNQdWX1xurq